// <auto-generated />
using System;
using LionSimPlanner.Scheduling.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LionSimPlanner.Scheduling.Infrastructure.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20260722063445_AddEarlyTerminationFields")]
    partial class AddEarlyTerminationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sched")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LionSimPlanner.Scheduling.Domain.Entities.SimulatorSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<Guid?>("CaptainId")
                        .HasColumnType("uuid")
                        .HasColumnName("captain_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid?>("EngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<Guid?>("FirstOfficerId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_officer_id");

                    b.Property<string>("GradeStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade_status");

                    b.Property<Guid?>("InstructorId")
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_id");

                    b.Property<string>("InstructorNotes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructor_notes");

                    b.Property<bool>("IsGraded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_graded");

                    b.Property<DateTime?>("OriginalEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_end_time");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("session_type");

                    b.Property<Guid>("SimulatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulator_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("SyllabusId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("syllabus_id");

                    b.Property<string>("TerminationReason")
                        .HasColumnType("text")
                        .HasColumnName("termination_reason");

                    b.Property<string>("TraineeEmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trainee_employee_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SessionId")
                        .HasName("pk_simulator_sessions");

                    b.HasIndex("SimulatorId")
                        .HasDatabaseName("idx_sessions_simulator_id");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("idx_sessions_start_time");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_sessions_status");

                    b.HasIndex("SimulatorId", "Status", "StartTime")
                        .HasDatabaseName("idx_sessions_aog_lookup");

                    b.ToTable("simulator_sessions", "sched");
                });
#pragma warning restore 612, 618
        }
    }
}
