// <auto-generated />
using System;
using LionSimPlanner.Asset.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LionSimPlanner.Asset.Infrastructure.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20260719164844_AddMaintenanceLifecycleEntities")]
    partial class AddMaintenanceLifecycleEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maint")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LionSimPlanner.Asset.Domain.Entities.Engineer", b =>
                {
                    b.Property<Guid>("EngineerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkout_time");

                    b.Property<string>("ClearanceLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clearance_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("HardwareRatings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hardware_ratings");

                    b.Property<bool>("IsOnCall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_on_call");

                    b.Property<DateTime>("ShiftEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shift_end_time");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shift_start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EngineerID");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("engineers", "maint");
                });

            modelBuilder.Entity("LionSimPlanner.Asset.Domain.Entities.MaintenanceChecklist", b =>
                {
                    b.Property<Guid>("ChecklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("checklist_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BlockingReason")
                        .HasColumnType("text")
                        .HasColumnName("blocking_reason");

                    b.Property<DateOnly>("ChecklistDate")
                        .HasColumnType("date")
                        .HasColumnName("checklist_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EngineerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("engineer_code");

                    b.Property<Guid>("EngineerIdRef")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id_ref");

                    b.Property<bool>("IsCleared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cleared");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("SignedOffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_off_at");

                    b.Property<Guid>("SimulatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulator_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ChecklistId");

                    b.HasIndex("SimulatorId", "ChecklistDate")
                        .IsUnique()
                        .HasDatabaseName("uq_checklist_simulator_date");

                    b.ToTable("maintenance_checklists", "maint");
                });

            modelBuilder.Entity("LionSimPlanner.Asset.Domain.Entities.MaintenanceLog", b =>
                {
                    b.Property<Guid>("MaintenanceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_log_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FaultDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fault_description");

                    b.Property<string>("ResolutionDescription")
                        .HasColumnType("text")
                        .HasColumnName("resolution_description");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SimulatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulator_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MaintenanceLogId");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("idx_maintenance_logs_resolved_at");

                    b.HasIndex("SimulatorId")
                        .HasDatabaseName("idx_maintenance_logs_simulator_id");

                    b.ToTable("maintenance_logs", "maint");
                });

            modelBuilder.Entity("LionSimPlanner.Asset.Domain.Entities.Simulator", b =>
                {
                    b.Property<Guid>("SimulatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("simulator_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aircraft_type");

                    b.Property<string>("BayNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bay_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastStatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_changed_at");

                    b.Property<string>("LastStatusChangedByEngineerCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_status_changed_by_engineer_code");

                    b.Property<Guid?>("LastStatusChangedByEngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_status_changed_by_engineer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Ready")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SimulatorId");

                    b.ToTable("simulators", "maint");
                });

            modelBuilder.Entity("LionSimPlanner.Asset.Domain.Entities.MaintenanceLog", b =>
                {
                    b.HasOne("LionSimPlanner.Asset.Domain.Entities.Simulator", "Simulator")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("SimulatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulator");
                });

            modelBuilder.Entity("LionSimPlanner.Asset.Domain.Entities.Simulator", b =>
                {
                    b.Navigation("MaintenanceLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
