// <auto-generated />
using System;
using LionSimPlanner.Personnel.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LionSimPlanner.Personnel.Infrastructure.Migrations
{
    [DbContext(typeof(PersonnelDbContext))]
    partial class PersonnelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LionSimPlanner.Personnel.Domain.Entities.Instructor", b =>
                {
                    b.Property<Guid>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthorizedSyllabi")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("authorized_syllabi");

                    b.Property<string>("CertifiedTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("certified_types");

                    b.Property<string>("CorporateEmail")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("corporate_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentMonthlyHours")
                        .HasColumnType("integer")
                        .HasColumnName("current_monthly_hours");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("LastDutyEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_duty_end_time");

                    b.Property<DateTime>("LicenseExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("license_expiry");

                    b.Property<int>("MaxMonthlyHours")
                        .HasColumnType("integer")
                        .HasColumnName("max_monthly_hours");

                    b.Property<DateTime>("NextDutyStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_duty_start_time");

                    b.Property<string>("RoleLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role_level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InstructorId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("instructors", "hr");
                });

            modelBuilder.Entity("LionSimPlanner.Personnel.Domain.Entities.Pilot", b =>
                {
                    b.Property<Guid>("PilotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pilot_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CorporateEmail")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("corporate_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("LastDutyEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_duty_end_time");

                    b.Property<DateTime>("LastTrainingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_training_date");

                    b.Property<DateTime>("MedicalExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("medical_expiry");

                    b.Property<DateTime>("NextDutyStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_duty_start_time");

                    b.Property<DateTime>("NextTrainingDue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_training_due");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rank");

                    b.Property<string>("RequiredSyllabus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("required_syllabus");

                    b.Property<string>("TypeRatings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("type_ratings");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PilotId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("pilots", "hr");
                });
#pragma warning restore 612, 618
        }
    }
}
